export const COUNTRY_FLAGS_AND_DIAL_CODES = [
    { name: 'France', code: 'FR', dialCode: '+33', flagUrl: 'https://flagcdn.com/fr.svg' },
    { name: 'Germany', code: 'DE', dialCode: '+49', flagUrl: 'https://flagcdn.com/de.svg' },
    { name: 'United Kingdom', code: 'GB', dialCode: '+44', flagUrl: 'https://flagcdn.com/gb.svg' },
    { name: 'United States', code: 'US', dialCode: '+1', flagUrl: 'https://flagcdn.com/us.svg' },
    { name: 'Canada', code: 'CA', dialCode: '+1', flagUrl: 'https://flagcdn.com/ca.svg' },
    { name: 'Italy', code: 'IT', dialCode: '+39', flagUrl: 'https://flagcdn.com/it.svg' },
    { name: 'Spain', code: 'ES', dialCode: '+34', flagUrl: 'https://flagcdn.com/es.svg' },
    { name: 'Portugal', code: 'PT', dialCode: '+351', flagUrl: 'https://flagcdn.com/pt.svg' },
    { name: 'Netherlands', code: 'NL', dialCode: '+31', flagUrl: 'https://flagcdn.com/nl.svg' },
    { name: 'Belgium', code: 'BE', dialCode: '+32', flagUrl: 'https://flagcdn.com/be.svg' },
    { name: 'Switzerland', code: 'CH', dialCode: '+41', flagUrl: 'https://flagcdn.com/ch.svg' },
    { name: 'Austria', code: 'AT', dialCode: '+43', flagUrl: 'https://flagcdn.com/at.svg' },
    { name: 'Sweden', code: 'SE', dialCode: '+46', flagUrl: 'https://flagcdn.com/se.svg' },
    { name: 'Norway', code: 'NO', dialCode: '+47', flagUrl: 'https://flagcdn.com/no.svg' },
    { name: 'Finland', code: 'FI', dialCode: '+358', flagUrl: 'https://flagcdn.com/fi.svg' },
    { name: 'Denmark', code: 'DK', dialCode: '+45', flagUrl: 'https://flagcdn.com/dk.svg' },
    { name: 'Poland', code: 'PL', dialCode: '+48', flagUrl: 'https://flagcdn.com/pl.svg' },
    { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flagUrl: 'https://flagcdn.com/cz.svg' },
    { name: 'Slovakia', code: 'SK', dialCode: '+421', flagUrl: 'https://flagcdn.com/sk.svg' },
    { name: 'Hungary', code: 'HU', dialCode: '+36', flagUrl: 'https://flagcdn.com/hu.svg' },
    { name: 'Greece', code: 'GR', dialCode: '+30', flagUrl: 'https://flagcdn.com/gr.svg' },
    { name: 'Romania', code: 'RO', dialCode: '+40', flagUrl: 'https://flagcdn.com/ro.svg' },
    { name: 'Ireland', code: 'IE', dialCode: '+353', flagUrl: 'https://flagcdn.com/ie.svg' },
    { name: 'Luxembourg', code: 'LU', dialCode: '+352', flagUrl: 'https://flagcdn.com/lu.svg' },
    { name: 'Estonia', code: 'EE', dialCode: '+372', flagUrl: 'https://flagcdn.com/ee.svg' },
    { name: 'Lithuania', code: 'LT', dialCode: '+370', flagUrl: 'https://flagcdn.com/lt.svg' },
    { name: 'Latvia', code: 'LV', dialCode: '+371', flagUrl: 'https://flagcdn.com/lv.svg' },
    { name: 'Slovenia', code: 'SI', dialCode: '+386', flagUrl: 'https://flagcdn.com/si.svg' },
    { name: 'Croatia', code: 'HR', dialCode: '+385', flagUrl: 'https://flagcdn.com/hr.svg' }
];