export const COUNTRY_FLAGS_AND_DIAL_CODES = [
    { name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷' },
    { name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪' },
    { name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧' },
    { name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸' },
    { name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦' },
    { name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹' },
    { name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸' },
    { name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹' },
    { name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱' },
    { name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪' },
    { name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭' },
    { name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹' },
    { name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪' },
    { name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴' },
    { name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮' },
    { name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰' },
    { name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱' },
    { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flag: '🇨🇿' },
    { name: 'Slovakia', code: 'SK', dialCode: '+421', flag: '🇸🇰' },
    { name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺' },
    { name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷' },
    { name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴' },
    { name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪' },
    { name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺' },
    { name: 'Estonia', code: 'EE', dialCode: '+372', flag: '🇪🇪' },
    { name: 'Lithuania', code: 'LT', dialCode: '+370', flag: '🇱🇹' },
    { name: 'Latvia', code: 'LV', dialCode: '+371', flag: '🇱🇻' },
    { name: 'Slovenia', code: 'SI', dialCode: '+386', flag: '🇸🇮' },
    { name: 'Croatia', code: 'HR', dialCode: '+385', flag: '🇭🇷' }
]