import { SocialMedia } from "../../core/models/social-media";

export const WORLD_DATA = [
  { id: 'DE', label: 'Baden Württemberg', value: 148 },
  { id: 'DE', label: 'Bayern', value: 31 },
  { id: 'DE', label: 'Berlin', value: 84 },
  { id: 'DE', label: 'Hambourg', value: 284 },
  { id: 'DE', label: 'Nordrhein - Westfalen', value: 170 },
  { id: 'DE', label: 'Nordrhein - Westfalen Bis', value: 60 },
  { id: 'DE', label: 'Hessen', value: 158 },
  { id: 'GB', label: 'Nguissi Mère (London)', value: 209 },
  { id: 'GB', label: 'Nguissi Nord (Manchester)', value: 151 },
  { id: 'GB', label: 'Birmingham', value: 288 },
  { id: 'AU', label: 'Australie', value: 259 },
  { id: 'AT', label: 'Autriche', value: 199 },
  { id: 'BE', label: 'Belgique Mère', value: 119 },
  { id: 'BE', label: 'Linoyoi li Belgique', value: 297 },
  { id: 'BE', label: 'Mawanda ma Belgique Mère', value: 105 },
  { id: 'BE', label: 'Nsebla u Belgique', value: 99 },
  { id: 'ES', label: 'Barcelone', value: 226 },
  { id: 'ES', label: 'Madrid', value: 38 },
  { id: 'ES', label: 'Nem Masse ma Bilbao', value: 237 },
  { id: 'FR', label: 'Bilama bi Côte d’Azur', value: 293 },
  { id: 'FR', label: 'Bordeaux', value: 134 },
  { id: 'FR', label: 'Cœur de Lyon', value: 71 },
  { id: 'FR', label: 'Cœur de Toulouse', value: 109 },
  { id: 'FR', label: "Côte d'azur Monaco", value: 257 },
  { id: 'FR', label: 'Gloire de Lyon', value: 93 },
  { id: 'FR', label: 'Grand Est', value: 207 },
  { id: 'FR', label: 'Grand Ouest', value: 150 },
  { id: 'FR', label: 'La Lorraine', value: 95 },
  { id: 'FR', label: 'Le Mans Mère', value: 57 },
  { id: 'FR', label: 'Like li nkeke li Lyon', value: 163 },
  { id: 'FR', label: 'Makwassi ma Lyon', value: 45 },
  { id: 'FR', label: 'Mivag mi Grand Est', value: 173 },
  { id: 'FR', label: 'Marseille', value: 32 },
  { id: 'FR', label: 'Masse ma Lyon', value: 135 },
  { id: 'FR', label: 'Mère de Lyon', value: 107 },
  { id: 'FR', label: 'Paris Adna', value: 71 },
  { id: 'FR', label: 'Paris Ambiance', value: 157 },
  { id: 'FR', label: 'Paris Bisai -', value: 294 },
  { id: 'FR', label: 'Paris Bords de Marne', value: 246 },
  { id: 'FR', label: 'Paris Centre', value: 188 },
  { id: 'FR', label: 'Paris Espoir', value: 193 },
  { id: 'FR', label: 'Paris Est Mère', value: 73 },
  { id: 'FR', label: 'Paris Est Etoile', value: 77 },
  { id: 'FR', label: 'Paris Est Karis', value: 11 },
  { id: 'FR', label: 'Paris Est Normandie', value: 198 },
  { id: 'FR', label: 'Paris Est Rive de Seine', value: 264 },
  { id: 'FR', label: 'Paris Est Sanaga', value: 73 },
  { id: 'FR', label: 'Paris Est Victoire', value: 154 },
  { id: 'FR', label: 'Paris Est Village', value: 111 },
  { id: 'FR', label: 'Paris Grand Nord', value: 235 },
  { id: 'FR', label: 'Paris Hémle', value: 284 },
  { id: 'FR', label: 'Paris Lipém -', value: 87 },
  { id: 'FR', label: 'Paris Lumière', value: 297 },
  { id: 'FR', label: 'Paris Maéba', value: 202 },
  { id: 'FR', label: 'Paris Maliga', value: 177 },
  { id: 'FR', label: 'Paris Maliga 18ième -', value: 28 },
  { id: 'FR', label: 'Paris Mahol', value: 236 },
  { id: 'FR', label: 'Paris Manogla', value: 15 },
  { id: 'FR', label: 'Paris Midi Convivialité', value: 151 },
  { id: 'FR', label: 'Paris Midi Express', value: 59 },
  { id: 'FR', label: 'Paris Midi Mère', value: 235 },
  { id: 'IT', label: 'Florence', value: 167 },
  { id: 'IT', label: 'Milan Mère', value: 284 },
  { id: 'IT', label: 'Porta di Roma', value: 75 },
  { id: 'IT', label: 'Rome', value: 204 },
  { id: 'LU', label: 'Trois Frontières', value: 162 },
  { id: 'NL', label: 'Hollande', value: 64 },
  { id: 'CH', label: 'Mahol ma Suisse', value: 211 },
  { id: 'CH', label: 'Mane ma Suisse', value: 120 },
  { id: 'US', label: 'USA Mère', value: 182 },
  { id: 'US', label: 'Libak li America', value: 239 },
  { id: 'US', label: 'Liyomba li America', value: 81 },
  { id: 'US', label: 'Massoda ma America', value: 40 },
  { id: 'US', label: 'Minkwel mi America', value: 118 },
  { id: 'JP', label: 'Tokyo', value: 264 }
]